[package]
name = "pgvector"
version = "0.1.0"
description = "pgvector support for Rust"
repository = "https://github.com/ankane/pgvector-rust"
license = "MIT OR Apache-2.0"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2018"
readme = "README.md"

[dependencies]
byteorder = "1"
bytes = "1"
postgres-types = "0"

[dev-dependencies]
postgres = "0"
