[package]
name = "pgvector"
version = "0.1.1"
description = "pgvector support for Rust"
repository = "https://github.com/ankane/pgvector-rust"
license = "MIT OR Apache-2.0"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2018"
readme = "README.md"

[dependencies]
byteorder = "1"
bytes = "1"
postgres = { version = "0", optional = true }
diesel = { version = "1", features = ["postgres"], optional = true }

[features]
default = ["postgres"]
