name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - uses: ankane/setup-postgres@v1
      with:
        database: pgvector_rs_test
    - run: bundle exec rake test
    - run: |
        sudo apt-get update && sudo apt-get install postgresql-server-dev-13
        git clone --branch v0.1.5 https://github.com/ankane/pgvector.git
        cd pgvector
        make
        sudo make install
    - run: cargo test
