name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: ankane/setup-postgres@v1
      with:
        database: pgvector_rust_test
    - run: |
        sudo apt-get update && sudo apt-get install postgresql-server-dev-14
        git clone --branch v0.3.0 https://github.com/pgvector/pgvector.git
        cd pgvector
        make
        sudo make install

    # test features individually
    - run: cargo test --features postgres
    - run: cargo test --features sqlx
    - run: cargo test --features diesel
